/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8736ba80-7d9e-42e5-85f2-53b25a4801d7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_VwEVY1zEL",
    "aws_user_pools_web_client_id": "6a7t0q0n8h6b6gqp5blicnfthl",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

// Torna o objeto globalmente acessível no navegador
window.awsconfig = awsmobile;
